---
- name: remove ppa
  apt_repository:
    repo: ppa:graphics-drivers/ppa
    state: absent

- name: add key
  apt_key:
    url: "{{ nvidia_driver_ubuntu_cuda_repo_gpgkey_url }}"
    id: "{{ nvidia_driver_ubuntu_cuda_repo_gpgkey_id }}"

- name: add repo
  apt_repository:
    repo: "deb {{ nvidia_driver_ubuntu_cuda_repo_baseurl }} /"
    update_cache: yes

- name: install driver packages
  apt:
    name: "{{ nvidia_driver_package_version | ternary('cuda-drivers='+nvidia_driver_package_version, 'cuda-drivers') }}"
    state: "{{ nvidia_driver_package_state }}"
    autoremove: "{{ nvidia_driver_package_state == 'absent' }}"
    purge: "{{ nvidia_driver_package_state == 'absent' }}"
  register: install_driver
